# Generated by Django 5.1.15 on 2026-09-20 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('CONSTRUCTIVE', 'Constructive'), ('REWARDS', 'Rewards'), ('OBSERVATION', 'Observation'), ('PROGRESS', 'Progress'), ('TRAINING', 'Training'), ('SATISFACTORY', 'Satisfactory'), ('PRAISE', 'Praise'), ('COACHING', 'Coaching'), ('SUGGESTION', 'Suggestion'), ('GENERAL', 'General')], default='POSITIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback')),
            ],
            options={
                'verbose_name': 'Feedback Comment',
                'verbose_name_plural': 'Feedback Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
