# Generated by Django 5.1.15 on 2026-09-19 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_alter_employeeprofile_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Evidence Submission',
                'verbose_name_plural': 'Evidence Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
