# Generated by Django 5.1.15 on 2026-09-19 09:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(default='Intern', max_length=100)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
