# Generated by Django 5.1.15 on 2026-09-19 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
