# Generated by Django 5.1.15 on 2026-09-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeprofile_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='competencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
