# Generated by Django 5.1.15 on 2026-09-19 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeprofile_joining_date'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appraisal_type', models.CharField(choices=[('SELF', 'Self Assessment'), ('MANAGER', 'Manager Evaluation'), ('ANNUAL_REVIEW', 'Annual Review')], default='MANAGER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('HR_APPROVED', 'HR Approved'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=20)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('self_comments', models.TextField(blank=True, null=True)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('final_comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employeeprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appraisals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal',
                'verbose_name_plural': 'Appraisals',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle', 'appraisal_type')},
            },
        ),
        migrations.CreateModel(
            name='AppraisalRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance.appraisal')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance.evaluationcriterion')),
            ],
            options={
                'verbose_name': 'Appraisal Rating',
                'verbose_name_plural': 'Appraisal Ratings',
                'unique_together': {('appraisal', 'criterion')},
            },
        ),
    ]
