# Generated by Django 5.1.15 on 2026-09-19 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeprofile_joining_date'),
        ('performance', '0002_appraisal_appraisalrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceImprovementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('objectives', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('SUCCESSFUL', 'Successful'), ('EXTENDED', 'Extended'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pips', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Performance Improvement Plan',
                'verbose_name_plural': 'Performance Improvement Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_rewards', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recognition & Reward',
                'verbose_name_plural': 'Recognition & Rewards',
                'ordering': ['-awarded_at'],
            },
        ),
    ]
